// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpredict_tiled.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPredict_tiled_CfgInitialize(XPredict_tiled *InstancePtr, XPredict_tiled_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPredict_tiled_Start(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPredict_tiled_IsDone(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPredict_tiled_IsIdle(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPredict_tiled_IsReady(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPredict_tiled_EnableAutoRestart(XPredict_tiled *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XPredict_tiled_DisableAutoRestart(XPredict_tiled *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XPredict_tiled_Set_length_x(XPredict_tiled *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_LENGTH_X_DATA, Data);
}

u32 XPredict_tiled_Get_length_x(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_LENGTH_X_DATA);
    return Data;
}

void XPredict_tiled_Set_length_dc(XPredict_tiled *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_LENGTH_DC_DATA, Data);
}

u32 XPredict_tiled_Get_length_dc(XPredict_tiled *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_LENGTH_DC_DATA);
    return Data;
}

void XPredict_tiled_InterruptGlobalEnable(XPredict_tiled *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_GIE, 1);
}

void XPredict_tiled_InterruptGlobalDisable(XPredict_tiled *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_GIE, 0);
}

void XPredict_tiled_InterruptEnable(XPredict_tiled *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_IER);
    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XPredict_tiled_InterruptDisable(XPredict_tiled *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_IER);
    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XPredict_tiled_InterruptClear(XPredict_tiled *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredict_tiled_WriteReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XPredict_tiled_InterruptGetEnabled(XPredict_tiled *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_IER);
}

u32 XPredict_tiled_InterruptGetStatus(XPredict_tiled *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredict_tiled_ReadReg(InstancePtr->Control_bus_BaseAddress, XPREDICT_TILED_CONTROL_BUS_ADDR_ISR);
}

