// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_1_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_1_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_1_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_1_proc::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_1_proc::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> Loop_1_proc::ap_ST_fsm_state4 = "100";
const sc_lv<32> Loop_1_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_1_proc::ap_const_boolean_1 = true;
const sc_lv<1> Loop_1_proc::ap_const_lv1_0 = "0";
const sc_lv<1> Loop_1_proc::ap_const_lv1_1 = "1";
const sc_lv<2> Loop_1_proc::ap_const_lv2_0 = "00";
const sc_lv<2> Loop_1_proc::ap_const_lv2_2 = "10";
const sc_lv<2> Loop_1_proc::ap_const_lv2_3 = "11";
const sc_lv<2> Loop_1_proc::ap_const_lv2_1 = "1";
const sc_lv<32> Loop_1_proc::ap_const_lv32_1 = "1";
const bool Loop_1_proc::ap_const_boolean_0 = false;
const sc_lv<9> Loop_1_proc::ap_const_lv9_0 = "000000000";
const sc_lv<10> Loop_1_proc::ap_const_lv10_0 = "0000000000";
const sc_lv<9> Loop_1_proc::ap_const_lv9_188 = "110001000";
const sc_lv<9> Loop_1_proc::ap_const_lv9_1 = "1";
const sc_lv<10> Loop_1_proc::ap_const_lv10_1 = "1";
const sc_lv<10> Loop_1_proc::ap_const_lv10_2 = "10";
const sc_lv<32> Loop_1_proc::ap_const_lv32_2 = "10";

Loop_1_proc::Loop_1_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_stream1_dest_V_0_vld_out );
    sensitive << ( in_stream2_dest_V_0_vld_out );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_stream1_dest_V_0_vld_out );
    sensitive << ( in_stream2_dest_V_0_vld_out );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( in_stream1_dest_V_0_vld_out );
    sensitive << ( in_stream2_dest_V_0_vld_out );
    sensitive << ( exitcond_i_i_reg_241 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_i_i_fu_187_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_exitcond_i_i_fu_187_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( is_idx1_0_i_i_reg_164 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_fu_235_p2);
    sensitive << ( i_0_i_i_reg_175 );

    SC_METHOD(thread_in_stream1_TDATA_blk_n);
    sensitive << ( in_stream1_data_V_0_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_i_reg_241 );

    SC_METHOD(thread_in_stream1_TREADY);
    sensitive << ( in_stream1_dest_V_0_state );

    SC_METHOD(thread_in_stream1_data_V_0_ack_in);
    sensitive << ( in_stream1_data_V_0_state );

    SC_METHOD(thread_in_stream1_data_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_in_stream1_data_V_0_data_out);
    sensitive << ( in_stream1_data_V_0_payload_A );
    sensitive << ( in_stream1_data_V_0_payload_B );
    sensitive << ( in_stream1_data_V_0_sel );

    SC_METHOD(thread_in_stream1_data_V_0_load_A);
    sensitive << ( in_stream1_data_V_0_sel_wr );
    sensitive << ( in_stream1_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_stream1_data_V_0_load_B);
    sensitive << ( in_stream1_data_V_0_sel_wr );
    sensitive << ( in_stream1_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_stream1_data_V_0_sel);
    sensitive << ( in_stream1_data_V_0_sel_rd );

    SC_METHOD(thread_in_stream1_data_V_0_state_cmp_full);
    sensitive << ( in_stream1_data_V_0_state );

    SC_METHOD(thread_in_stream1_data_V_0_vld_in);
    sensitive << ( in_stream1_TVALID );

    SC_METHOD(thread_in_stream1_data_V_0_vld_out);
    sensitive << ( in_stream1_data_V_0_state );

    SC_METHOD(thread_in_stream1_dest_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_in_stream1_dest_V_0_vld_in);
    sensitive << ( in_stream1_TVALID );

    SC_METHOD(thread_in_stream1_dest_V_0_vld_out);
    sensitive << ( in_stream1_dest_V_0_state );

    SC_METHOD(thread_in_stream2_TDATA_blk_n);
    sensitive << ( in_stream2_data_V_0_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_i_reg_241 );

    SC_METHOD(thread_in_stream2_TREADY);
    sensitive << ( in_stream2_dest_V_0_state );

    SC_METHOD(thread_in_stream2_data_V_0_ack_in);
    sensitive << ( in_stream2_data_V_0_state );

    SC_METHOD(thread_in_stream2_data_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_in_stream2_data_V_0_data_out);
    sensitive << ( in_stream2_data_V_0_payload_A );
    sensitive << ( in_stream2_data_V_0_payload_B );
    sensitive << ( in_stream2_data_V_0_sel );

    SC_METHOD(thread_in_stream2_data_V_0_load_A);
    sensitive << ( in_stream2_data_V_0_sel_wr );
    sensitive << ( in_stream2_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_stream2_data_V_0_load_B);
    sensitive << ( in_stream2_data_V_0_sel_wr );
    sensitive << ( in_stream2_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_stream2_data_V_0_sel);
    sensitive << ( in_stream2_data_V_0_sel_rd );

    SC_METHOD(thread_in_stream2_data_V_0_state_cmp_full);
    sensitive << ( in_stream2_data_V_0_state );

    SC_METHOD(thread_in_stream2_data_V_0_vld_in);
    sensitive << ( in_stream2_TVALID );

    SC_METHOD(thread_in_stream2_data_V_0_vld_out);
    sensitive << ( in_stream2_data_V_0_state );

    SC_METHOD(thread_in_stream2_dest_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_in_stream2_dest_V_0_vld_in);
    sensitive << ( in_stream2_TVALID );

    SC_METHOD(thread_in_stream2_dest_V_0_vld_out);
    sensitive << ( in_stream2_dest_V_0_state );

    SC_METHOD(thread_is_idx1_fu_193_p2);
    sensitive << ( is_idx1_0_i_i_reg_164 );

    SC_METHOD(thread_temp2_buf_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_fu_208_p1 );

    SC_METHOD(thread_temp2_buf_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_4_i_fu_220_p1 );

    SC_METHOD(thread_temp2_buf_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp2_buf_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp2_buf_d0);
    sensitive << ( in_stream2_data_V_0_data_out );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_temp2_buf_d1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_temp2_buf_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp2_buf_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp_buf_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_fu_208_p1 );

    SC_METHOD(thread_temp_buf_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_4_i_fu_220_p1 );

    SC_METHOD(thread_temp_buf_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp_buf_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp_buf_d0);
    sensitive << ( in_stream1_data_V_0_data_out );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_temp_buf_d1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_temp_buf_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_temp_buf_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_i_reg_241 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_2_i_fu_208_p1);
    sensitive << ( i_0_i_i_reg_175 );

    SC_METHOD(thread_tmp_3_i_fu_214_p2);
    sensitive << ( i_0_i_i_reg_175 );

    SC_METHOD(thread_tmp_4_i_fu_220_p1);
    sensitive << ( tmp_3_i_fu_214_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_i_i_fu_187_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    in_stream1_data_V_0_sel_rd = SC_LOGIC_0;
    in_stream1_data_V_0_sel_wr = SC_LOGIC_0;
    in_stream1_data_V_0_state = "00";
    in_stream1_dest_V_0_state = "00";
    in_stream2_data_V_0_sel_rd = SC_LOGIC_0;
    in_stream2_data_V_0_sel_wr = SC_LOGIC_0;
    in_stream2_data_V_0_state = "00";
    in_stream2_dest_V_0_state = "00";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_1_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_stream1_TDATA, "(port)in_stream1_TDATA");
    sc_trace(mVcdFile, in_stream1_TVALID, "(port)in_stream1_TVALID");
    sc_trace(mVcdFile, in_stream1_TREADY, "(port)in_stream1_TREADY");
    sc_trace(mVcdFile, in_stream1_TSTRB, "(port)in_stream1_TSTRB");
    sc_trace(mVcdFile, in_stream1_TKEEP, "(port)in_stream1_TKEEP");
    sc_trace(mVcdFile, in_stream1_TUSER, "(port)in_stream1_TUSER");
    sc_trace(mVcdFile, in_stream1_TLAST, "(port)in_stream1_TLAST");
    sc_trace(mVcdFile, in_stream1_TID, "(port)in_stream1_TID");
    sc_trace(mVcdFile, in_stream1_TDEST, "(port)in_stream1_TDEST");
    sc_trace(mVcdFile, temp_buf_address0, "(port)temp_buf_address0");
    sc_trace(mVcdFile, temp_buf_ce0, "(port)temp_buf_ce0");
    sc_trace(mVcdFile, temp_buf_we0, "(port)temp_buf_we0");
    sc_trace(mVcdFile, temp_buf_d0, "(port)temp_buf_d0");
    sc_trace(mVcdFile, temp_buf_address1, "(port)temp_buf_address1");
    sc_trace(mVcdFile, temp_buf_ce1, "(port)temp_buf_ce1");
    sc_trace(mVcdFile, temp_buf_we1, "(port)temp_buf_we1");
    sc_trace(mVcdFile, temp_buf_d1, "(port)temp_buf_d1");
    sc_trace(mVcdFile, in_stream2_TDATA, "(port)in_stream2_TDATA");
    sc_trace(mVcdFile, in_stream2_TVALID, "(port)in_stream2_TVALID");
    sc_trace(mVcdFile, in_stream2_TREADY, "(port)in_stream2_TREADY");
    sc_trace(mVcdFile, in_stream2_TSTRB, "(port)in_stream2_TSTRB");
    sc_trace(mVcdFile, in_stream2_TKEEP, "(port)in_stream2_TKEEP");
    sc_trace(mVcdFile, in_stream2_TUSER, "(port)in_stream2_TUSER");
    sc_trace(mVcdFile, in_stream2_TLAST, "(port)in_stream2_TLAST");
    sc_trace(mVcdFile, in_stream2_TID, "(port)in_stream2_TID");
    sc_trace(mVcdFile, in_stream2_TDEST, "(port)in_stream2_TDEST");
    sc_trace(mVcdFile, temp2_buf_address0, "(port)temp2_buf_address0");
    sc_trace(mVcdFile, temp2_buf_ce0, "(port)temp2_buf_ce0");
    sc_trace(mVcdFile, temp2_buf_we0, "(port)temp2_buf_we0");
    sc_trace(mVcdFile, temp2_buf_d0, "(port)temp2_buf_d0");
    sc_trace(mVcdFile, temp2_buf_address1, "(port)temp2_buf_address1");
    sc_trace(mVcdFile, temp2_buf_ce1, "(port)temp2_buf_ce1");
    sc_trace(mVcdFile, temp2_buf_we1, "(port)temp2_buf_we1");
    sc_trace(mVcdFile, temp2_buf_d1, "(port)temp2_buf_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_stream1_data_V_0_data_out, "in_stream1_data_V_0_data_out");
    sc_trace(mVcdFile, in_stream1_data_V_0_vld_in, "in_stream1_data_V_0_vld_in");
    sc_trace(mVcdFile, in_stream1_data_V_0_vld_out, "in_stream1_data_V_0_vld_out");
    sc_trace(mVcdFile, in_stream1_data_V_0_ack_in, "in_stream1_data_V_0_ack_in");
    sc_trace(mVcdFile, in_stream1_data_V_0_ack_out, "in_stream1_data_V_0_ack_out");
    sc_trace(mVcdFile, in_stream1_data_V_0_payload_A, "in_stream1_data_V_0_payload_A");
    sc_trace(mVcdFile, in_stream1_data_V_0_payload_B, "in_stream1_data_V_0_payload_B");
    sc_trace(mVcdFile, in_stream1_data_V_0_sel_rd, "in_stream1_data_V_0_sel_rd");
    sc_trace(mVcdFile, in_stream1_data_V_0_sel_wr, "in_stream1_data_V_0_sel_wr");
    sc_trace(mVcdFile, in_stream1_data_V_0_sel, "in_stream1_data_V_0_sel");
    sc_trace(mVcdFile, in_stream1_data_V_0_load_A, "in_stream1_data_V_0_load_A");
    sc_trace(mVcdFile, in_stream1_data_V_0_load_B, "in_stream1_data_V_0_load_B");
    sc_trace(mVcdFile, in_stream1_data_V_0_state, "in_stream1_data_V_0_state");
    sc_trace(mVcdFile, in_stream1_data_V_0_state_cmp_full, "in_stream1_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, in_stream1_dest_V_0_vld_in, "in_stream1_dest_V_0_vld_in");
    sc_trace(mVcdFile, in_stream1_dest_V_0_vld_out, "in_stream1_dest_V_0_vld_out");
    sc_trace(mVcdFile, in_stream1_dest_V_0_ack_out, "in_stream1_dest_V_0_ack_out");
    sc_trace(mVcdFile, in_stream1_dest_V_0_state, "in_stream1_dest_V_0_state");
    sc_trace(mVcdFile, in_stream2_data_V_0_data_out, "in_stream2_data_V_0_data_out");
    sc_trace(mVcdFile, in_stream2_data_V_0_vld_in, "in_stream2_data_V_0_vld_in");
    sc_trace(mVcdFile, in_stream2_data_V_0_vld_out, "in_stream2_data_V_0_vld_out");
    sc_trace(mVcdFile, in_stream2_data_V_0_ack_in, "in_stream2_data_V_0_ack_in");
    sc_trace(mVcdFile, in_stream2_data_V_0_ack_out, "in_stream2_data_V_0_ack_out");
    sc_trace(mVcdFile, in_stream2_data_V_0_payload_A, "in_stream2_data_V_0_payload_A");
    sc_trace(mVcdFile, in_stream2_data_V_0_payload_B, "in_stream2_data_V_0_payload_B");
    sc_trace(mVcdFile, in_stream2_data_V_0_sel_rd, "in_stream2_data_V_0_sel_rd");
    sc_trace(mVcdFile, in_stream2_data_V_0_sel_wr, "in_stream2_data_V_0_sel_wr");
    sc_trace(mVcdFile, in_stream2_data_V_0_sel, "in_stream2_data_V_0_sel");
    sc_trace(mVcdFile, in_stream2_data_V_0_load_A, "in_stream2_data_V_0_load_A");
    sc_trace(mVcdFile, in_stream2_data_V_0_load_B, "in_stream2_data_V_0_load_B");
    sc_trace(mVcdFile, in_stream2_data_V_0_state, "in_stream2_data_V_0_state");
    sc_trace(mVcdFile, in_stream2_data_V_0_state_cmp_full, "in_stream2_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, in_stream2_dest_V_0_vld_in, "in_stream2_dest_V_0_vld_in");
    sc_trace(mVcdFile, in_stream2_dest_V_0_vld_out, "in_stream2_dest_V_0_vld_out");
    sc_trace(mVcdFile, in_stream2_dest_V_0_ack_out, "in_stream2_dest_V_0_ack_out");
    sc_trace(mVcdFile, in_stream2_dest_V_0_state, "in_stream2_dest_V_0_state");
    sc_trace(mVcdFile, in_stream1_TDATA_blk_n, "in_stream1_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_i_i_reg_241, "exitcond_i_i_reg_241");
    sc_trace(mVcdFile, in_stream2_TDATA_blk_n, "in_stream2_TDATA_blk_n");
    sc_trace(mVcdFile, is_idx1_0_i_i_reg_164, "is_idx1_0_i_i_reg_164");
    sc_trace(mVcdFile, i_0_i_i_reg_175, "i_0_i_i_reg_175");
    sc_trace(mVcdFile, exitcond_i_i_fu_187_p2, "exitcond_i_i_fu_187_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, is_idx1_fu_193_p2, "is_idx1_fu_193_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, i_fu_235_p2, "i_fu_235_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, tmp_2_i_fu_208_p1, "tmp_2_i_fu_208_p1");
    sc_trace(mVcdFile, tmp_4_i_fu_220_p1, "tmp_4_i_fu_220_p1");
    sc_trace(mVcdFile, tmp_3_i_fu_214_p2, "tmp_3_i_fu_214_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Loop_1_proc::~Loop_1_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Loop_1_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_0_i_i_reg_175 = i_fu_235_p2.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_0_i_i_reg_175 = ap_const_lv10_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream1_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_vld_out.read()))) {
            in_stream1_data_V_0_sel_rd =  (sc_logic) (~in_stream1_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream1_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_ack_in.read()))) {
            in_stream1_data_V_0_sel_wr =  (sc_logic) (~in_stream1_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream1_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_2)))) {
            in_stream1_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_1)))) {
            in_stream1_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(in_stream1_data_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_ack_out.read()))))) {
            in_stream1_data_V_0_state = ap_const_lv2_3;
        } else {
            in_stream1_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream1_dest_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_stream1_dest_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_stream1_dest_V_0_state.read())))) {
            in_stream1_dest_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_stream1_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream1_dest_V_0_state.read())))) {
            in_stream1_dest_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_stream1_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream1_dest_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_stream1_dest_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_dest_V_0_ack_out.read()))))) {
            in_stream1_dest_V_0_state = ap_const_lv2_3;
        } else {
            in_stream1_dest_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream2_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_vld_out.read()))) {
            in_stream2_data_V_0_sel_rd =  (sc_logic) (~in_stream2_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream2_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_ack_in.read()))) {
            in_stream2_data_V_0_sel_wr =  (sc_logic) (~in_stream2_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream2_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_data_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_stream2_data_V_0_state.read())))) {
            in_stream2_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_data_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream2_data_V_0_state.read())))) {
            in_stream2_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_stream2_data_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream2_data_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_data_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_ack_out.read()))))) {
            in_stream2_data_V_0_state = ap_const_lv2_3;
        } else {
            in_stream2_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        in_stream2_dest_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_dest_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_stream2_dest_V_0_state.read())))) {
            in_stream2_dest_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream2_dest_V_0_state.read())))) {
            in_stream2_dest_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_stream2_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_stream2_dest_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_stream2_dest_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_dest_V_0_ack_out.read()))))) {
            in_stream2_dest_V_0_state = ap_const_lv2_3;
        } else {
            in_stream2_dest_V_0_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_fu_187_p2.read()))) {
        is_idx1_0_i_i_reg_164 = is_idx1_fu_193_p2.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        is_idx1_0_i_i_reg_164 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_i_i_reg_241 = exitcond_i_i_fu_187_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_load_A.read())) {
        in_stream1_data_V_0_payload_A = in_stream1_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_load_B.read())) {
        in_stream1_data_V_0_payload_B = in_stream1_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_load_A.read())) {
        in_stream2_data_V_0_payload_A = in_stream2_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_load_B.read())) {
        in_stream2_data_V_0_payload_B = in_stream2_TDATA.read();
    }
}

void Loop_1_proc::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Loop_1_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_1_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void Loop_1_proc::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_1_proc::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_out.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_out.read()))));
}

void Loop_1_proc::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_out.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_out.read()))));
}

void Loop_1_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_1_proc::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_1_proc::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream1_dest_V_0_vld_out.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream2_dest_V_0_vld_out.read())));
}

void Loop_1_proc::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_i_i_fu_187_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_1_proc::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_1_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_exitcond_i_i_fu_187_p2() {
    exitcond_i_i_fu_187_p2 = (!is_idx1_0_i_i_reg_164.read().is_01() || !ap_const_lv9_188.is_01())? sc_lv<1>(): sc_lv<1>(is_idx1_0_i_i_reg_164.read() == ap_const_lv9_188);
}

void Loop_1_proc::thread_i_fu_235_p2() {
    i_fu_235_p2 = (!i_0_i_i_reg_175.read().is_01() || !ap_const_lv10_2.is_01())? sc_lv<10>(): (sc_biguint<10>(i_0_i_i_reg_175.read()) + sc_biguint<10>(ap_const_lv10_2));
}

void Loop_1_proc::thread_in_stream1_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()))) {
        in_stream1_TDATA_blk_n = in_stream1_data_V_0_state.read()[0];
    } else {
        in_stream1_TDATA_blk_n = ap_const_logic_1;
    }
}

void Loop_1_proc::thread_in_stream1_TREADY() {
    in_stream1_TREADY = in_stream1_dest_V_0_state.read()[1];
}

void Loop_1_proc::thread_in_stream1_data_V_0_ack_in() {
    in_stream1_data_V_0_ack_in = in_stream1_data_V_0_state.read()[1];
}

void Loop_1_proc::thread_in_stream1_data_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_stream1_data_V_0_ack_out = ap_const_logic_1;
    } else {
        in_stream1_data_V_0_ack_out = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_in_stream1_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream1_data_V_0_sel.read())) {
        in_stream1_data_V_0_data_out = in_stream1_data_V_0_payload_B.read();
    } else {
        in_stream1_data_V_0_data_out = in_stream1_data_V_0_payload_A.read();
    }
}

void Loop_1_proc::thread_in_stream1_data_V_0_load_A() {
    in_stream1_data_V_0_load_A = (in_stream1_data_V_0_state_cmp_full.read() & ~in_stream1_data_V_0_sel_wr.read());
}

void Loop_1_proc::thread_in_stream1_data_V_0_load_B() {
    in_stream1_data_V_0_load_B = (in_stream1_data_V_0_sel_wr.read() & in_stream1_data_V_0_state_cmp_full.read());
}

void Loop_1_proc::thread_in_stream1_data_V_0_sel() {
    in_stream1_data_V_0_sel = in_stream1_data_V_0_sel_rd.read();
}

void Loop_1_proc::thread_in_stream1_data_V_0_state_cmp_full() {
    in_stream1_data_V_0_state_cmp_full =  (sc_logic) ((!in_stream1_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_stream1_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void Loop_1_proc::thread_in_stream1_data_V_0_vld_in() {
    in_stream1_data_V_0_vld_in = in_stream1_TVALID.read();
}

void Loop_1_proc::thread_in_stream1_data_V_0_vld_out() {
    in_stream1_data_V_0_vld_out = in_stream1_data_V_0_state.read()[0];
}

void Loop_1_proc::thread_in_stream1_dest_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_stream1_dest_V_0_ack_out = ap_const_logic_1;
    } else {
        in_stream1_dest_V_0_ack_out = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_in_stream1_dest_V_0_vld_in() {
    in_stream1_dest_V_0_vld_in = in_stream1_TVALID.read();
}

void Loop_1_proc::thread_in_stream1_dest_V_0_vld_out() {
    in_stream1_dest_V_0_vld_out = in_stream1_dest_V_0_state.read()[0];
}

void Loop_1_proc::thread_in_stream2_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()))) {
        in_stream2_TDATA_blk_n = in_stream2_data_V_0_state.read()[0];
    } else {
        in_stream2_TDATA_blk_n = ap_const_logic_1;
    }
}

void Loop_1_proc::thread_in_stream2_TREADY() {
    in_stream2_TREADY = in_stream2_dest_V_0_state.read()[1];
}

void Loop_1_proc::thread_in_stream2_data_V_0_ack_in() {
    in_stream2_data_V_0_ack_in = in_stream2_data_V_0_state.read()[1];
}

void Loop_1_proc::thread_in_stream2_data_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_stream2_data_V_0_ack_out = ap_const_logic_1;
    } else {
        in_stream2_data_V_0_ack_out = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_in_stream2_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_stream2_data_V_0_sel.read())) {
        in_stream2_data_V_0_data_out = in_stream2_data_V_0_payload_B.read();
    } else {
        in_stream2_data_V_0_data_out = in_stream2_data_V_0_payload_A.read();
    }
}

void Loop_1_proc::thread_in_stream2_data_V_0_load_A() {
    in_stream2_data_V_0_load_A = (in_stream2_data_V_0_state_cmp_full.read() & ~in_stream2_data_V_0_sel_wr.read());
}

void Loop_1_proc::thread_in_stream2_data_V_0_load_B() {
    in_stream2_data_V_0_load_B = (in_stream2_data_V_0_sel_wr.read() & in_stream2_data_V_0_state_cmp_full.read());
}

void Loop_1_proc::thread_in_stream2_data_V_0_sel() {
    in_stream2_data_V_0_sel = in_stream2_data_V_0_sel_rd.read();
}

void Loop_1_proc::thread_in_stream2_data_V_0_state_cmp_full() {
    in_stream2_data_V_0_state_cmp_full =  (sc_logic) ((!in_stream2_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_stream2_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void Loop_1_proc::thread_in_stream2_data_V_0_vld_in() {
    in_stream2_data_V_0_vld_in = in_stream2_TVALID.read();
}

void Loop_1_proc::thread_in_stream2_data_V_0_vld_out() {
    in_stream2_data_V_0_vld_out = in_stream2_data_V_0_state.read()[0];
}

void Loop_1_proc::thread_in_stream2_dest_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_stream2_dest_V_0_ack_out = ap_const_logic_1;
    } else {
        in_stream2_dest_V_0_ack_out = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_in_stream2_dest_V_0_vld_in() {
    in_stream2_dest_V_0_vld_in = in_stream2_TVALID.read();
}

void Loop_1_proc::thread_in_stream2_dest_V_0_vld_out() {
    in_stream2_dest_V_0_vld_out = in_stream2_dest_V_0_state.read()[0];
}

void Loop_1_proc::thread_is_idx1_fu_193_p2() {
    is_idx1_fu_193_p2 = (!is_idx1_0_i_i_reg_164.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(is_idx1_0_i_i_reg_164.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void Loop_1_proc::thread_temp2_buf_address0() {
    temp2_buf_address0 =  (sc_lv<10>) (tmp_2_i_fu_208_p1.read());
}

void Loop_1_proc::thread_temp2_buf_address1() {
    temp2_buf_address1 =  (sc_lv<10>) (tmp_4_i_fu_220_p1.read());
}

void Loop_1_proc::thread_temp2_buf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp2_buf_ce0 = ap_const_logic_1;
    } else {
        temp2_buf_ce0 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp2_buf_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp2_buf_ce1 = ap_const_logic_1;
    } else {
        temp2_buf_ce1 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp2_buf_d0() {
    temp2_buf_d0 = in_stream2_data_V_0_data_out.read();
}

void Loop_1_proc::thread_temp2_buf_d1() {
    temp2_buf_d1 = ap_const_lv32_0;
}

void Loop_1_proc::thread_temp2_buf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp2_buf_we0 = ap_const_logic_1;
    } else {
        temp2_buf_we0 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp2_buf_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp2_buf_we1 = ap_const_logic_1;
    } else {
        temp2_buf_we1 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp_buf_address0() {
    temp_buf_address0 =  (sc_lv<10>) (tmp_2_i_fu_208_p1.read());
}

void Loop_1_proc::thread_temp_buf_address1() {
    temp_buf_address1 =  (sc_lv<10>) (tmp_4_i_fu_220_p1.read());
}

void Loop_1_proc::thread_temp_buf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp_buf_ce0 = ap_const_logic_1;
    } else {
        temp_buf_ce0 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp_buf_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp_buf_ce1 = ap_const_logic_1;
    } else {
        temp_buf_ce1 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp_buf_d0() {
    temp_buf_d0 = in_stream1_data_V_0_data_out.read();
}

void Loop_1_proc::thread_temp_buf_d1() {
    temp_buf_d1 = ap_const_lv32_0;
}

void Loop_1_proc::thread_temp_buf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp_buf_we0 = ap_const_logic_1;
    } else {
        temp_buf_we0 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_temp_buf_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_241.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp_buf_we1 = ap_const_logic_1;
    } else {
        temp_buf_we1 = ap_const_logic_0;
    }
}

void Loop_1_proc::thread_tmp_2_i_fu_208_p1() {
    tmp_2_i_fu_208_p1 = esl_zext<64,10>(i_0_i_i_reg_175.read());
}

void Loop_1_proc::thread_tmp_3_i_fu_214_p2() {
    tmp_3_i_fu_214_p2 = (i_0_i_i_reg_175.read() | ap_const_lv10_1);
}

void Loop_1_proc::thread_tmp_4_i_fu_220_p1() {
    tmp_4_i_fu_220_p1 = esl_zext<64,10>(tmp_3_i_fu_214_p2.read());
}

void Loop_1_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(exitcond_i_i_fu_187_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(exitcond_i_i_fu_187_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

