// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XHARDWARE_ACCELERATOR_H
#define XHARDWARE_ACCELERATOR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xhardware_accelerator_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XHardware_accelerator_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XHardware_accelerator;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XHardware_accelerator_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XHardware_accelerator_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XHardware_accelerator_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XHardware_accelerator_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XHardware_accelerator_Initialize(XHardware_accelerator *InstancePtr, u16 DeviceId);
XHardware_accelerator_Config* XHardware_accelerator_LookupConfig(u16 DeviceId);
int XHardware_accelerator_CfgInitialize(XHardware_accelerator *InstancePtr, XHardware_accelerator_Config *ConfigPtr);
#else
int XHardware_accelerator_Initialize(XHardware_accelerator *InstancePtr, const char* InstanceName);
int XHardware_accelerator_Release(XHardware_accelerator *InstancePtr);
#endif

void XHardware_accelerator_Start(XHardware_accelerator *InstancePtr);
u32 XHardware_accelerator_IsDone(XHardware_accelerator *InstancePtr);
u32 XHardware_accelerator_IsIdle(XHardware_accelerator *InstancePtr);
u32 XHardware_accelerator_IsReady(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_EnableAutoRestart(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_DisableAutoRestart(XHardware_accelerator *InstancePtr);

void XHardware_accelerator_Set_function_flag(XHardware_accelerator *InstancePtr, u32 Data);
u32 XHardware_accelerator_Get_function_flag(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_Set_length_x(XHardware_accelerator *InstancePtr, u32 Data);
u32 XHardware_accelerator_Get_length_x(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_Set_tile_count(XHardware_accelerator *InstancePtr, u32 Data);
u32 XHardware_accelerator_Get_tile_count(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_Set_dual_coeff_length(XHardware_accelerator *InstancePtr, u32 Data);
u32 XHardware_accelerator_Get_dual_coeff_length(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_Set_remainder(XHardware_accelerator *InstancePtr, u32 Data);
u32 XHardware_accelerator_Get_remainder(XHardware_accelerator *InstancePtr);

void XHardware_accelerator_InterruptGlobalEnable(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_InterruptGlobalDisable(XHardware_accelerator *InstancePtr);
void XHardware_accelerator_InterruptEnable(XHardware_accelerator *InstancePtr, u32 Mask);
void XHardware_accelerator_InterruptDisable(XHardware_accelerator *InstancePtr, u32 Mask);
void XHardware_accelerator_InterruptClear(XHardware_accelerator *InstancePtr, u32 Mask);
u32 XHardware_accelerator_InterruptGetEnabled(XHardware_accelerator *InstancePtr);
u32 XHardware_accelerator_InterruptGetStatus(XHardware_accelerator *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
