// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _kernel_matrix_HH_
#define _kernel_matrix_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Loop_LOOP_1_proc10.h"
#include "Loop_LOOP_2_proc9.h"
#include "Loop_LOOP_6_proc.h"
#include "kernel_matrix_indibs.h"
#include "kernel_matrix_resjbC.h"
#include "fifo_w32_d3_A.h"
#include "fifo_w32_d2_A.h"
#include "kernel_matrix_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct kernel_matrix : public sc_module {
    // Port declarations 47
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_in< sc_lv<32> > kernel_in_stream_TDATA;
    sc_in< sc_lv<4> > kernel_in_stream_TKEEP;
    sc_in< sc_lv<4> > kernel_in_stream_TSTRB;
    sc_in< sc_lv<4> > kernel_in_stream_TUSER;
    sc_in< sc_lv<1> > kernel_in_stream_TLAST;
    sc_in< sc_lv<5> > kernel_in_stream_TID;
    sc_in< sc_lv<5> > kernel_in_stream_TDEST;
    sc_in< sc_lv<32> > kernel_index_stream_TDATA;
    sc_in< sc_lv<4> > kernel_index_stream_TKEEP;
    sc_in< sc_lv<4> > kernel_index_stream_TSTRB;
    sc_in< sc_lv<4> > kernel_index_stream_TUSER;
    sc_in< sc_lv<1> > kernel_index_stream_TLAST;
    sc_in< sc_lv<5> > kernel_index_stream_TID;
    sc_in< sc_lv<5> > kernel_index_stream_TDEST;
    sc_out< sc_lv<32> > kernel_out_stream_TDATA;
    sc_out< sc_lv<4> > kernel_out_stream_TKEEP;
    sc_out< sc_lv<4> > kernel_out_stream_TSTRB;
    sc_out< sc_lv<4> > kernel_out_stream_TUSER;
    sc_out< sc_lv<1> > kernel_out_stream_TLAST;
    sc_out< sc_lv<5> > kernel_out_stream_TID;
    sc_out< sc_lv<5> > kernel_out_stream_TDEST;
    sc_in< sc_logic > kernel_index_stream_TVALID;
    sc_out< sc_logic > kernel_index_stream_TREADY;
    sc_in< sc_logic > kernel_in_stream_TVALID;
    sc_out< sc_logic > kernel_in_stream_TREADY;
    sc_out< sc_logic > kernel_out_stream_TVALID;
    sc_in< sc_logic > kernel_out_stream_TREADY;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const2;
    sc_signal< sc_logic > ap_var_for_const1;


    // Module declarations
    kernel_matrix(sc_module_name name);
    SC_HAS_PROCESS(kernel_matrix);

    ~kernel_matrix();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    kernel_matrix_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* kernel_matrix_CONTROL_BUS_s_axi_U;
    kernel_matrix_indibs* index_buf_U;
    kernel_matrix_resjbC* result_buf_U;
    Loop_LOOP_1_proc10* Loop_LOOP_1_proc10_U0;
    Loop_LOOP_2_proc9* Loop_LOOP_2_proc9_U0;
    Loop_LOOP_6_proc* Loop_LOOP_6_proc_U0;
    fifo_w32_d3_A* length_x_c_U;
    fifo_w32_d2_A* tile_size_c_U;
    fifo_w32_d2_A* remaining_size_c_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<32> > length_x;
    sc_signal< sc_lv<32> > tile_size;
    sc_signal< sc_lv<32> > remaining_size;
    sc_signal< sc_lv<32> > index_buf_i_q0;
    sc_signal< sc_lv<32> > index_buf_t_q0;
    sc_signal< sc_lv<32> > result_buf_i_q0;
    sc_signal< sc_lv<32> > result_buf_t_q0;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_ap_start;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_ap_done;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_ap_continue;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_ap_idle;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_ap_ready;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_kernel_index_stream_TREADY;
    sc_signal< sc_lv<10> > Loop_LOOP_1_proc10_U0_index_buf_address0;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_index_buf_ce0;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_index_buf_we0;
    sc_signal< sc_lv<32> > Loop_LOOP_1_proc10_U0_index_buf_d0;
    sc_signal< sc_lv<32> > Loop_LOOP_1_proc10_U0_length_x_out_din;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_length_x_out_write;
    sc_signal< sc_lv<32> > Loop_LOOP_1_proc10_U0_tile_size_out_din;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_tile_size_out_write;
    sc_signal< sc_lv<32> > Loop_LOOP_1_proc10_U0_remaining_size_out_din;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_remaining_size_out_write;
    sc_signal< sc_logic > ap_channel_done_index_buf;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_index_buf_full_n;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_ap_start;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_ap_done;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_ap_continue;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_ap_idle;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_ap_ready;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_tile_size_read;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_remaining_size_read;
    sc_signal< sc_lv<12> > Loop_LOOP_2_proc9_U0_result_buf_address0;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_result_buf_ce0;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_result_buf_we0;
    sc_signal< sc_lv<32> > Loop_LOOP_2_proc9_U0_result_buf_d0;
    sc_signal< sc_lv<10> > Loop_LOOP_2_proc9_U0_index_buf_address0;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_index_buf_ce0;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_kernel_in_stream_TREADY;
    sc_signal< sc_logic > ap_channel_done_result_buf;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_result_buf_full_n;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_ap_ready;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_length_x_read;
    sc_signal< sc_lv<12> > Loop_LOOP_6_proc_U0_result_buf_address0;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_result_buf_ce0;
    sc_signal< sc_lv<32> > Loop_LOOP_6_proc_U0_kernel_out_stream_TDATA;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_kernel_out_stream_TVALID;
    sc_signal< sc_lv<4> > Loop_LOOP_6_proc_U0_kernel_out_stream_TKEEP;
    sc_signal< sc_lv<4> > Loop_LOOP_6_proc_U0_kernel_out_stream_TSTRB;
    sc_signal< sc_lv<4> > Loop_LOOP_6_proc_U0_kernel_out_stream_TUSER;
    sc_signal< sc_lv<1> > Loop_LOOP_6_proc_U0_kernel_out_stream_TLAST;
    sc_signal< sc_lv<5> > Loop_LOOP_6_proc_U0_kernel_out_stream_TID;
    sc_signal< sc_lv<5> > Loop_LOOP_6_proc_U0_kernel_out_stream_TDEST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > index_buf_i_full_n;
    sc_signal< sc_logic > index_buf_t_empty_n;
    sc_signal< sc_logic > result_buf_i_full_n;
    sc_signal< sc_logic > result_buf_t_empty_n;
    sc_signal< sc_logic > length_x_c_full_n;
    sc_signal< sc_lv<32> > length_x_c_dout;
    sc_signal< sc_logic > length_x_c_empty_n;
    sc_signal< sc_logic > tile_size_c_full_n;
    sc_signal< sc_lv<32> > tile_size_c_dout;
    sc_signal< sc_logic > tile_size_c_empty_n;
    sc_signal< sc_logic > remaining_size_c_full_n;
    sc_signal< sc_lv<32> > remaining_size_c_dout;
    sc_signal< sc_logic > remaining_size_c_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Loop_LOOP_1_proc10_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Loop_LOOP_1_proc10_U0_ap_ready;
    sc_signal< sc_lv<2> > Loop_LOOP_1_proc10_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_Loop_LOOP_2_proc9_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Loop_LOOP_2_proc9_U0_ap_ready;
    sc_signal< sc_lv<2> > Loop_LOOP_2_proc9_U0_ap_ready_count;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_start_full_n;
    sc_signal< sc_logic > Loop_LOOP_1_proc10_U0_start_write;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_start_full_n;
    sc_signal< sc_logic > Loop_LOOP_2_proc9_U0_start_write;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_start_full_n;
    sc_signal< sc_logic > Loop_LOOP_6_proc_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_Loop_LOOP_1_proc10_U0_ap_continue();
    void thread_Loop_LOOP_1_proc10_U0_ap_start();
    void thread_Loop_LOOP_1_proc10_U0_index_buf_full_n();
    void thread_Loop_LOOP_1_proc10_U0_start_full_n();
    void thread_Loop_LOOP_1_proc10_U0_start_write();
    void thread_Loop_LOOP_2_proc9_U0_ap_continue();
    void thread_Loop_LOOP_2_proc9_U0_ap_start();
    void thread_Loop_LOOP_2_proc9_U0_result_buf_full_n();
    void thread_Loop_LOOP_2_proc9_U0_start_full_n();
    void thread_Loop_LOOP_2_proc9_U0_start_write();
    void thread_Loop_LOOP_6_proc_U0_ap_continue();
    void thread_Loop_LOOP_6_proc_U0_ap_start();
    void thread_Loop_LOOP_6_proc_U0_start_full_n();
    void thread_Loop_LOOP_6_proc_U0_start_write();
    void thread_ap_channel_done_index_buf();
    void thread_ap_channel_done_result_buf();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_Loop_LOOP_1_proc10_U0_ap_ready();
    void thread_ap_sync_Loop_LOOP_2_proc9_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_kernel_in_stream_TREADY();
    void thread_kernel_index_stream_TREADY();
    void thread_kernel_out_stream_TDATA();
    void thread_kernel_out_stream_TDEST();
    void thread_kernel_out_stream_TID();
    void thread_kernel_out_stream_TKEEP();
    void thread_kernel_out_stream_TLAST();
    void thread_kernel_out_stream_TSTRB();
    void thread_kernel_out_stream_TUSER();
    void thread_kernel_out_stream_TVALID();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
