// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtiled_kernel_matrix.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTiled_kernel_matrix_CfgInitialize(XTiled_kernel_matrix *InstancePtr, XTiled_kernel_matrix_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTiled_kernel_matrix_Start(XTiled_kernel_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTiled_kernel_matrix_IsDone(XTiled_kernel_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTiled_kernel_matrix_IsIdle(XTiled_kernel_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTiled_kernel_matrix_IsReady(XTiled_kernel_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTiled_kernel_matrix_EnableAutoRestart(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XTiled_kernel_matrix_DisableAutoRestart(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XTiled_kernel_matrix_Set_length_x(XTiled_kernel_matrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_LENGTH_X_DATA, Data);
}

u32 XTiled_kernel_matrix_Get_length_x(XTiled_kernel_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_LENGTH_X_DATA);
    return Data;
}

void XTiled_kernel_matrix_InterruptGlobalEnable(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_GIE, 1);
}

void XTiled_kernel_matrix_InterruptGlobalDisable(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_GIE, 0);
}

void XTiled_kernel_matrix_InterruptEnable(XTiled_kernel_matrix *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_IER);
    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XTiled_kernel_matrix_InterruptDisable(XTiled_kernel_matrix *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_IER);
    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XTiled_kernel_matrix_InterruptClear(XTiled_kernel_matrix *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTiled_kernel_matrix_WriteReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XTiled_kernel_matrix_InterruptGetEnabled(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_IER);
}

u32 XTiled_kernel_matrix_InterruptGetStatus(XTiled_kernel_matrix *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTiled_kernel_matrix_ReadReg(InstancePtr->Control_bus_BaseAddress, XTILED_KERNEL_MATRIX_CONTROL_BUS_ADDR_ISR);
}

