-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_1_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream1_TVALID : IN STD_LOGIC;
    in_stream1_TREADY : OUT STD_LOGIC;
    in_stream1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream1_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    in_stream1_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
    temp_buf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    temp_buf_ce0 : OUT STD_LOGIC;
    temp_buf_we0 : OUT STD_LOGIC;
    temp_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    temp_buf_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    temp_buf_ce1 : OUT STD_LOGIC;
    temp_buf_we1 : OUT STD_LOGIC;
    temp_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_stream2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream2_TVALID : IN STD_LOGIC;
    in_stream2_TREADY : OUT STD_LOGIC;
    in_stream2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream2_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    in_stream2_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
    temp2_buf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    temp2_buf_ce0 : OUT STD_LOGIC;
    temp2_buf_we0 : OUT STD_LOGIC;
    temp2_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    temp2_buf_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    temp2_buf_ce1 : OUT STD_LOGIC;
    temp2_buf_we1 : OUT STD_LOGIC;
    temp2_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Loop_1_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv9_188 : STD_LOGIC_VECTOR (8 downto 0) := "110001000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_stream1_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream1_data_V_0_vld_in : STD_LOGIC;
    signal in_stream1_data_V_0_vld_out : STD_LOGIC;
    signal in_stream1_data_V_0_ack_in : STD_LOGIC;
    signal in_stream1_data_V_0_ack_out : STD_LOGIC;
    signal in_stream1_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream1_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream1_data_V_0_sel_rd : STD_LOGIC := '0';
    signal in_stream1_data_V_0_sel_wr : STD_LOGIC := '0';
    signal in_stream1_data_V_0_sel : STD_LOGIC;
    signal in_stream1_data_V_0_load_A : STD_LOGIC;
    signal in_stream1_data_V_0_load_B : STD_LOGIC;
    signal in_stream1_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream1_data_V_0_state_cmp_full : STD_LOGIC;
    signal in_stream1_dest_V_0_vld_in : STD_LOGIC;
    signal in_stream1_dest_V_0_vld_out : STD_LOGIC;
    signal in_stream1_dest_V_0_ack_out : STD_LOGIC;
    signal in_stream1_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream2_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream2_data_V_0_vld_in : STD_LOGIC;
    signal in_stream2_data_V_0_vld_out : STD_LOGIC;
    signal in_stream2_data_V_0_ack_in : STD_LOGIC;
    signal in_stream2_data_V_0_ack_out : STD_LOGIC;
    signal in_stream2_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream2_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream2_data_V_0_sel_rd : STD_LOGIC := '0';
    signal in_stream2_data_V_0_sel_wr : STD_LOGIC := '0';
    signal in_stream2_data_V_0_sel : STD_LOGIC;
    signal in_stream2_data_V_0_load_A : STD_LOGIC;
    signal in_stream2_data_V_0_load_B : STD_LOGIC;
    signal in_stream2_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream2_data_V_0_state_cmp_full : STD_LOGIC;
    signal in_stream2_dest_V_0_vld_in : STD_LOGIC;
    signal in_stream2_dest_V_0_vld_out : STD_LOGIC;
    signal in_stream2_dest_V_0_ack_out : STD_LOGIC;
    signal in_stream2_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream1_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_i_i_reg_241 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_stream2_TDATA_blk_n : STD_LOGIC;
    signal is_idx1_0_i_i_reg_164 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_0_i_i_reg_175 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond_i_i_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal is_idx1_fu_193_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal i_fu_235_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal tmp_2_i_fu_208_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_i_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_i_fu_214_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    in_stream1_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream1_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_stream1_data_V_0_ack_out = ap_const_logic_1) and (in_stream1_data_V_0_vld_out = ap_const_logic_1))) then 
                                        in_stream1_data_V_0_sel_rd <= not(in_stream1_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_stream1_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream1_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_stream1_data_V_0_ack_in = ap_const_logic_1) and (in_stream1_data_V_0_vld_in = ap_const_logic_1))) then 
                                        in_stream1_data_V_0_sel_wr <= not(in_stream1_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_stream1_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream1_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream1_data_V_0_state = ap_const_lv2_2) and (in_stream1_data_V_0_vld_in = ap_const_logic_0)) or ((in_stream1_data_V_0_state = ap_const_lv2_3) and (in_stream1_data_V_0_vld_in = ap_const_logic_0) and (in_stream1_data_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream1_data_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream1_data_V_0_state = ap_const_lv2_1) and (in_stream1_data_V_0_ack_out = ap_const_logic_0)) or ((in_stream1_data_V_0_state = ap_const_lv2_3) and (in_stream1_data_V_0_ack_out = ap_const_logic_0) and (in_stream1_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream1_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream1_data_V_0_vld_in = ap_const_logic_0) and (in_stream1_data_V_0_ack_out = ap_const_logic_1))) and not(((in_stream1_data_V_0_ack_out = ap_const_logic_0) and (in_stream1_data_V_0_vld_in = ap_const_logic_1))) and (in_stream1_data_V_0_state = ap_const_lv2_3)) or ((in_stream1_data_V_0_state = ap_const_lv2_1) and (in_stream1_data_V_0_ack_out = ap_const_logic_1)) or ((in_stream1_data_V_0_state = ap_const_lv2_2) and (in_stream1_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream1_data_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream1_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream1_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream1_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream1_dest_V_0_state = ap_const_lv2_2) and (in_stream1_dest_V_0_vld_in = ap_const_logic_0)) or ((in_stream1_dest_V_0_state = ap_const_lv2_3) and (in_stream1_dest_V_0_vld_in = ap_const_logic_0) and (in_stream1_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream1_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream1_dest_V_0_state = ap_const_lv2_1) and (in_stream1_dest_V_0_ack_out = ap_const_logic_0)) or ((in_stream1_dest_V_0_state = ap_const_lv2_3) and (in_stream1_dest_V_0_ack_out = ap_const_logic_0) and (in_stream1_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream1_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream1_dest_V_0_vld_in = ap_const_logic_0) and (in_stream1_dest_V_0_ack_out = ap_const_logic_1))) and not(((in_stream1_dest_V_0_ack_out = ap_const_logic_0) and (in_stream1_dest_V_0_vld_in = ap_const_logic_1))) and (in_stream1_dest_V_0_state = ap_const_lv2_3)) or ((in_stream1_dest_V_0_state = ap_const_lv2_1) and (in_stream1_dest_V_0_ack_out = ap_const_logic_1)) or ((in_stream1_dest_V_0_state = ap_const_lv2_2) and (in_stream1_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream1_dest_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream1_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream2_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream2_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_stream2_data_V_0_ack_out = ap_const_logic_1) and (in_stream2_data_V_0_vld_out = ap_const_logic_1))) then 
                                        in_stream2_data_V_0_sel_rd <= not(in_stream2_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_stream2_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream2_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_stream2_data_V_0_ack_in = ap_const_logic_1) and (in_stream2_data_V_0_vld_in = ap_const_logic_1))) then 
                                        in_stream2_data_V_0_sel_wr <= not(in_stream2_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_stream2_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream2_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream2_data_V_0_state = ap_const_lv2_2) and (in_stream2_data_V_0_vld_in = ap_const_logic_0)) or ((in_stream2_data_V_0_state = ap_const_lv2_3) and (in_stream2_data_V_0_vld_in = ap_const_logic_0) and (in_stream2_data_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream2_data_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream2_data_V_0_state = ap_const_lv2_1) and (in_stream2_data_V_0_ack_out = ap_const_logic_0)) or ((in_stream2_data_V_0_state = ap_const_lv2_3) and (in_stream2_data_V_0_ack_out = ap_const_logic_0) and (in_stream2_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream2_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream2_data_V_0_vld_in = ap_const_logic_0) and (in_stream2_data_V_0_ack_out = ap_const_logic_1))) and not(((in_stream2_data_V_0_ack_out = ap_const_logic_0) and (in_stream2_data_V_0_vld_in = ap_const_logic_1))) and (in_stream2_data_V_0_state = ap_const_lv2_3)) or ((in_stream2_data_V_0_state = ap_const_lv2_1) and (in_stream2_data_V_0_ack_out = ap_const_logic_1)) or ((in_stream2_data_V_0_state = ap_const_lv2_2) and (in_stream2_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream2_data_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream2_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream2_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream2_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream2_dest_V_0_state = ap_const_lv2_2) and (in_stream2_dest_V_0_vld_in = ap_const_logic_0)) or ((in_stream2_dest_V_0_state = ap_const_lv2_3) and (in_stream2_dest_V_0_vld_in = ap_const_logic_0) and (in_stream2_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream2_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream2_dest_V_0_state = ap_const_lv2_1) and (in_stream2_dest_V_0_ack_out = ap_const_logic_0)) or ((in_stream2_dest_V_0_state = ap_const_lv2_3) and (in_stream2_dest_V_0_ack_out = ap_const_logic_0) and (in_stream2_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream2_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream2_dest_V_0_vld_in = ap_const_logic_0) and (in_stream2_dest_V_0_ack_out = ap_const_logic_1))) and not(((in_stream2_dest_V_0_ack_out = ap_const_logic_0) and (in_stream2_dest_V_0_vld_in = ap_const_logic_1))) and (in_stream2_dest_V_0_state = ap_const_lv2_3)) or ((in_stream2_dest_V_0_state = ap_const_lv2_1) and (in_stream2_dest_V_0_ack_out = ap_const_logic_1)) or ((in_stream2_dest_V_0_state = ap_const_lv2_2) and (in_stream2_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream2_dest_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream2_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_i_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_i_i_reg_175 <= i_fu_235_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_i_reg_175 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    is_idx1_0_i_i_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                is_idx1_0_i_i_reg_164 <= is_idx1_fu_193_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                is_idx1_0_i_i_reg_164 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exitcond_i_i_reg_241 <= exitcond_i_i_fu_187_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream1_data_V_0_load_A = ap_const_logic_1)) then
                in_stream1_data_V_0_payload_A <= in_stream1_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream1_data_V_0_load_B = ap_const_logic_1)) then
                in_stream1_data_V_0_payload_B <= in_stream1_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream2_data_V_0_load_A = ap_const_logic_1)) then
                in_stream2_data_V_0_payload_A <= in_stream2_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream2_data_V_0_load_B = ap_const_logic_1)) then
                in_stream2_data_V_0_payload_B <= in_stream2_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, exitcond_i_i_fu_187_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_i_i_fu_187_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_i_i_fu_187_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(in_stream1_dest_V_0_vld_out, in_stream2_dest_V_0_vld_out, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream2_dest_V_0_vld_out = ap_const_logic_0)) or ((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream1_dest_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_stream1_dest_V_0_vld_out, in_stream2_dest_V_0_vld_out, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream2_dest_V_0_vld_out = ap_const_logic_0)) or ((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream1_dest_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(in_stream1_dest_V_0_vld_out, in_stream2_dest_V_0_vld_out, exitcond_i_i_reg_241)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream2_dest_V_0_vld_out = ap_const_logic_0)) or ((exitcond_i_i_reg_241 = ap_const_lv1_0) and (in_stream1_dest_V_0_vld_out = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_i_i_fu_187_p2)
    begin
        if ((exitcond_i_i_fu_187_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_i_i_fu_187_p2 <= "1" when (is_idx1_0_i_i_reg_164 = ap_const_lv9_188) else "0";
    i_fu_235_p2 <= std_logic_vector(unsigned(i_0_i_i_reg_175) + unsigned(ap_const_lv10_2));

    in_stream1_TDATA_blk_n_assign_proc : process(in_stream1_data_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_i_reg_241)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream1_TDATA_blk_n <= in_stream1_data_V_0_state(0);
        else 
            in_stream1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream1_TREADY <= in_stream1_dest_V_0_state(1);
    in_stream1_data_V_0_ack_in <= in_stream1_data_V_0_state(1);

    in_stream1_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream1_data_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream1_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_stream1_data_V_0_data_out_assign_proc : process(in_stream1_data_V_0_payload_A, in_stream1_data_V_0_payload_B, in_stream1_data_V_0_sel)
    begin
        if ((in_stream1_data_V_0_sel = ap_const_logic_1)) then 
            in_stream1_data_V_0_data_out <= in_stream1_data_V_0_payload_B;
        else 
            in_stream1_data_V_0_data_out <= in_stream1_data_V_0_payload_A;
        end if; 
    end process;

    in_stream1_data_V_0_load_A <= (in_stream1_data_V_0_state_cmp_full and not(in_stream1_data_V_0_sel_wr));
    in_stream1_data_V_0_load_B <= (in_stream1_data_V_0_state_cmp_full and in_stream1_data_V_0_sel_wr);
    in_stream1_data_V_0_sel <= in_stream1_data_V_0_sel_rd;
    in_stream1_data_V_0_state_cmp_full <= '0' when (in_stream1_data_V_0_state = ap_const_lv2_1) else '1';
    in_stream1_data_V_0_vld_in <= in_stream1_TVALID;
    in_stream1_data_V_0_vld_out <= in_stream1_data_V_0_state(0);

    in_stream1_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream1_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream1_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_stream1_dest_V_0_vld_in <= in_stream1_TVALID;
    in_stream1_dest_V_0_vld_out <= in_stream1_dest_V_0_state(0);

    in_stream2_TDATA_blk_n_assign_proc : process(in_stream2_data_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_i_reg_241)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream2_TDATA_blk_n <= in_stream2_data_V_0_state(0);
        else 
            in_stream2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream2_TREADY <= in_stream2_dest_V_0_state(1);
    in_stream2_data_V_0_ack_in <= in_stream2_data_V_0_state(1);

    in_stream2_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream2_data_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream2_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_stream2_data_V_0_data_out_assign_proc : process(in_stream2_data_V_0_payload_A, in_stream2_data_V_0_payload_B, in_stream2_data_V_0_sel)
    begin
        if ((in_stream2_data_V_0_sel = ap_const_logic_1)) then 
            in_stream2_data_V_0_data_out <= in_stream2_data_V_0_payload_B;
        else 
            in_stream2_data_V_0_data_out <= in_stream2_data_V_0_payload_A;
        end if; 
    end process;

    in_stream2_data_V_0_load_A <= (in_stream2_data_V_0_state_cmp_full and not(in_stream2_data_V_0_sel_wr));
    in_stream2_data_V_0_load_B <= (in_stream2_data_V_0_state_cmp_full and in_stream2_data_V_0_sel_wr);
    in_stream2_data_V_0_sel <= in_stream2_data_V_0_sel_rd;
    in_stream2_data_V_0_state_cmp_full <= '0' when (in_stream2_data_V_0_state = ap_const_lv2_1) else '1';
    in_stream2_data_V_0_vld_in <= in_stream2_TVALID;
    in_stream2_data_V_0_vld_out <= in_stream2_data_V_0_state(0);

    in_stream2_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream2_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream2_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_stream2_dest_V_0_vld_in <= in_stream2_TVALID;
    in_stream2_dest_V_0_vld_out <= in_stream2_dest_V_0_state(0);
    is_idx1_fu_193_p2 <= std_logic_vector(unsigned(is_idx1_0_i_i_reg_164) + unsigned(ap_const_lv9_1));
    temp2_buf_address0 <= tmp_2_i_fu_208_p1(10 - 1 downto 0);
    temp2_buf_address1 <= tmp_4_i_fu_220_p1(10 - 1 downto 0);

    temp2_buf_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp2_buf_ce0 <= ap_const_logic_1;
        else 
            temp2_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_buf_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp2_buf_ce1 <= ap_const_logic_1;
        else 
            temp2_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    temp2_buf_d0 <= in_stream2_data_V_0_data_out;
    temp2_buf_d1 <= ap_const_lv32_0;

    temp2_buf_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp2_buf_we0 <= ap_const_logic_1;
        else 
            temp2_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_buf_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp2_buf_we1 <= ap_const_logic_1;
        else 
            temp2_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;

    temp_buf_address0 <= tmp_2_i_fu_208_p1(10 - 1 downto 0);
    temp_buf_address1 <= tmp_4_i_fu_220_p1(10 - 1 downto 0);

    temp_buf_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_buf_ce0 <= ap_const_logic_1;
        else 
            temp_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp_buf_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_buf_ce1 <= ap_const_logic_1;
        else 
            temp_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    temp_buf_d0 <= in_stream1_data_V_0_data_out;
    temp_buf_d1 <= ap_const_lv32_0;

    temp_buf_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_buf_we0 <= ap_const_logic_1;
        else 
            temp_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp_buf_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_241, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_241 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_buf_we1 <= ap_const_logic_1;
        else 
            temp_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_i_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_i_reg_175),64));
    tmp_3_i_fu_214_p2 <= (i_0_i_i_reg_175 or ap_const_lv10_1);
    tmp_4_i_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_i_fu_214_p2),64));
end behav;
